### ISSUE TITLE
Missing data on GET /api​/ui​/resources

### ISSUE THREAD

**Issue by BastianWel** [FraunhoferISST/IDS-ConfigurationManager#21]
Missing:
ids:publisher
ids:standardLicense

**Comment by goekhanKahriman** [comment]
The publisher and standardlicense attributes expect a URI as input. Since the Infomodel 4.2.0 snapshot, URIs must have a certain format, which means that if you just enter a string, it will be evaluated as null. For example you have to enter a string with the following structure: http://license, then it will not be set as null and will be displayed.
