### ISSUE TITLE
NoClassDefFoundError on running Jar file

### ISSUE THREAD

**Issue by BastianWel** [FraunhoferISST/IDS-ConfigurationManager#8]
When building the project with `mvn clean package` and running the jar file, it stops with: 
`NoClassDefFoundError: de/fraunhofer/iais/eis/RouteStep`

**Comment by goekhanKahriman** [comment]
The problem is that we are using a newer version of the infomodel which is located in the lib folder at our site. This contains classes that do not yet exist in the infomodel, which is obtained from the Maven Reposi.

One possible solution at the moment is to go to the configmanager folder and call **mvn spring-boot:run** from the console.

**Comment by goekhanKahriman** [comment]
@BastianWel 
Update: The configmanager uses from now on the infomodel version 4.2.0-SNAPSHOT
starting the application with java -jar configurationmanager-1.0.1.jar should not cause any problems anymore
