### ISSUE TITLE
Error on PUT ​/api​/ui​/resource​/contract & POST /api/ui/resource/representation

### ISSUE THREAD

**Issue by BastianWel** [FraunhoferISST/IDS-ConfigurationManager#9]
`PUT ​/api​/ui​/resource​/contract` & `POST /api/ui/resource/representation` return  `"error": "Could not find any resources!"`.
The resource ID used as parameter exists.
`GET /api/ui/resource` with same ID returns resource.

**Comment by goekhanKahriman** [comment]
The errors are primarily due to the fact that no app routes have been created. It was agreed that now AppRoutes are always created at the beginning and then resources, representations and contracts are created and edited. With the current version of the feature branch and the prerequisite that AppRoutes exist, the APIs work.
